name: Rust Build

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.ref }}
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --verbose --release
    - name: Upload artifact (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: get-3gpp-spec-linux
        path: linux/get-3gpp-spec # 실제 프로젝트 실행 파일 경로로 변경
    - name: Upload artifact (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: get-3gpp-spec-windows
        path: windows/get-3gpp-spec.exe # 실제 프로젝트 실행 파일 경로로 변경
    - name: Upload artifact (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: get-3gpp-spec-macos
        path: macos/get-3gpp-spec # 실제 프로젝트 실행 파일 경로로 변경
